application: simple-timeline
version: rel-2015-01-12
runtime: go
api_version: go1

handlers:
- url: /event/new
  script: _go_app

- url: /search/new
  script: _go_app

- url: /.*
  script: _go_app
  login: admin
